services:
  hypervisor-monitor:
    image: pingouinfinihub/hypervisor-monitor:latest
    container_name: hypervisor-monitor
    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION:-dev}